services:
    php:
        build: ./.docker/php
        environment:
            APP_ENV: "test"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
            PHP_DATE_TIMEZONE: "Europe/Prague"
            COMPOSER_HOME: "/tmp"
            YARN_CACHE_FOLDER: "/tmp"
            HOME: "/tmp"
            XDEBUG_CONFIG: >-
                client_host=172.17.0.1
                client_port=9003
                remote_log=/tmp/xdebug.log
                log_level=0
                output_dir=/src/var/log
            XDEBUG_TRIGGER: "yes"
            XDEBUG_MODE: "debug"
            PHP_IDE_CONFIG: "serverName=3brsSyliusPaymentRestrictionsPlugin"
        volumes:
            - ./:/srv/sylius:delegated
            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
        depends_on:
            - mysql
        networks:
            - sylius

    nginx:
        build: ./.docker/nginx
        depends_on:
            - php
        volumes:
            - ./:/srv/sylius:delegated
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - "${APP_HOST_MAPPING_PORT:-8080}:80"
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - "${MYSQL_HOST_MAPPING_PORT:-3306}:3306"
        networks:
            - sylius

    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_USER: ${POSTGRES_USER:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        networks:
            - sylius

networks:
    sylius:
        driver: bridge

volumes:
    database_data:
