services:
    app:
        image: sylius/standard:1.11-traditional
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Prague"
        volumes:
            - ./:/app:delegated
            - ./:/var/www:delegated
#            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
#            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 8080:80 # http://localhost:8080
            - 8000:8000 # http://localhost:8000
        depends_on:
            - mysql
#            - postgres
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
            # Host port 0 is for "first available"
            # How to change it:
            # - set MYSQL_HOST_MAPPING_PORT variable in .env file for example
            # - or extends ports in docker-compose.override.yml
            # To find out used port use `docker ps` and look for PORTS column to see mapped host port, including IP it can be for example 0.0.0.0:32772 which is roughly equivalent to 127.0.0.1:32772 for internal network requests
            - "${MYSQL_HOST_MAPPING_PORT:-0}:3306"
        networks:
            - sylius

#    postgres:
#        image: postgres:14-alpine
#        environment:
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: postgres
#        ports:
#            - ${POSTGRES_PORT:-5432}:5432
#        networks:
#            - sylius

networks:
    sylius:
        driver: bridge
