services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ThreeBRS\SyliusPaymentRestrictionPlugin\Model\ThreeBRSSyliusResolvePaymentMethodForOrder:
        arguments:
            $zoneMatcher: '@sylius.zone_matcher'

    ThreeBRS\SyliusPaymentRestrictionPlugin\PaymentResolver\PaymentMethodsResolver:
        tags:
            - name: "sylius.payment_method_resolver"
              type: "channel_based"
              label: "sylius.payment_methods_resolver.channel_based"
              priority: 100
        arguments:
            $paymentMethodRepository: '@sylius.repository.payment_method'
            $paymentOrderResolver: '@ThreeBRS\SyliusPaymentRestrictionPlugin\Model\ThreeBRSSyliusResolvePaymentMethodForOrder'

    ThreeBRS\SyliusPaymentRestrictionPlugin\Form\Extension\RestrictionPaymentMethodExtension:
        tags:
            - extended_type: Sylius\Bundle\PaymentBundle\Form\Type\PaymentMethodType
              name: form.type_extension
        arguments:
            $shippingMethodClass: '%sylius.model.shipping_method.class%'
